# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f57eb291435d65919527966f3df9e69f3b159e398ee47756f803742eb62f8f55f3731be853d9a147c52b2894801b1d59e5035ba5f3c36f82db5272d5536ea3

test:
  secret_key_base: b8356098d67d769c09d1e0154c2965aa46082dedd1bf3c643d6af6843e09652f6155c233396ef4da3415264443f31fac56e9a82d14cd156b93fb66f2f558c68a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
